import Batgirl from "../../assets/Gotham-Knights-Batgirl-Gameplay-Trailer-Comic-Con-2022.avif";
import Shadow from "../../assets/Shadow.jpg";
import Robin from "../../assets/robin.avif";
import Renne from "../../assets/Renne.webp";
import RedHood from "../../assets/Red Hood.avif";
import Penguin from "../../assets/Penguin.webp";
import Owl from "../../assets/Owl.avif";
import Nightwing from "../../assets/Nightwing.avif";
import Lucius from "../../assets/lucius.jpg";
import Harley from "../../assets/Harley.jpeg";
import Freeze from "../../assets/freeze.jpg";
import Clay from "../../assets/clayface.jpg";
import Bruce from "../../assets/Bruce_Wayne.PNG.webp";

export const predefinedOptions = {
  fitnessGoals: [
    { value: "weight-loss", label: "Weight Loss" },
    { value: "muscle-gain", label: "Muscle Gain" },
    { value: "flexibility", label: "Flexibility" },
    { value: "endurance", label: "Endurance" },
    { value: "general-fitness", label: "General Fitness" },
    { value: "stress-relief", label: "Stress Relief" },
    { value: "cardio-health", label: "Cardio Health" },
    { value: "body-toning", label: "Body Toning" },
    { value: "posture-improvement", label: "Posture Improvement" },
    { value: "rehabilitation", label: "Rehabilitation" },
    { value: "weight-maintenance", label: "Weight Maintenance" },
    { value: "sports-performance", label: "Sports Performance" },
  ],
  workoutPreferences: [
    { value: "gym", label: "Gym" },
    { value: "yoga", label: "Yoga" },
    { value: "running", label: "Running" },
    { value: "swimming", label: "Swimming" },
    { value: "cycling", label: "Cycling" },
    { value: "home-workouts", label: "Home Workouts" },
    { value: "hiking", label: "Hiking" },
    { value: "pilates", label: "Pilates" },
    { value: "aerobics", label: "Aerobics" },
    { value: "crossfit", label: "CrossFit" },
    { value: "dance", label: "Dance" },
    { value: "martial-arts", label: "Martial Arts" },
    { value: "team-sports", label: "Team Sports" },
    { value: "rock-climbing", label: "Rock Climbing" },
    { value: "boxing", label: "Boxing" },
  ],
  activityType: [
    { value: "strength-training", label: "Strength Training" },
    { value: "cardio", label: "Cardio" },
    { value: "stretching", label: "Stretching" },
    { value: "outdoor-activities", label: "Outdoor Activities" },
    { value: "indoor-activities", label: "Indoor Activities" },
    { value: "water-sports", label: "Water Sports" },
    { value: "team-games", label: "Team Games" },
    { value: "mindfulness", label: "Mindfulness" },
    { value: "interval-training", label: "Interval Training" },
    { value: "sports-training", label: "Sports Training" },
    { value: "bodyweight-exercises", label: "Bodyweight Exercises" },
    { value: "balance-training", label: "Balance Training" },
    { value: "calisthenics", label: "Calisthenics" },
    { value: "plyometrics", label: "Plyometrics" },
  ],
  availability: [
    { value: "morning", label: "Morning (5 AM - 9 AM)" },
    { value: "mid-morning", label: "Mid-Morning (9 AM - 12 PM)" },
    { value: "afternoon", label: "Afternoon (12 PM - 4 PM)" },
    { value: "evening", label: "Evening (4 PM - 8 PM)" },
    { value: "night", label: "Night (8 PM - 11 PM)" },
    { value: "weekends", label: "Weekends" },
    { value: "weekdays", label: "Weekdays" },
    { value: "flexible", label: "Flexible Schedule" },
    { value: "early-morning", label: "Early Morning (4 AM - 5 AM)" },
    { value: "late-night", label: "Late Night (11 PM - 1 AM)" },
  ],
  schedule: [
    { value: "daily", label: "Daily" },
    { value: "every-other-day", label: "Every Other Day" },
    { value: "weekdays-only", label: "Weekdays Only" },
    { value: "weekends-only", label: "Weekends Only" },
    { value: "three-times-a-week", label: "Three Times a Week" },
    { value: "twice-a-week", label: "Twice a Week" },
    { value: "once-a-week", label: "Once a Week" },
    { value: "custom-schedule", label: "Custom Schedule" },
    { value: "monthly", label: "Monthly" },
  ],
  fitnessLevels: [
    { value: "sedentary", label: "Sedentary" },
    { value: "lightly-active", label: "Lightly Active" },
    { value: "moderately-active", label: "Moderately Active" },
    { value: "active", label: "Active" },
    { value: "athletic", label: "Athletic" },
    { value: "highly-active", label: "Highly Active" },
    { value: "professional-athlete", label: "Professional Athlete" },
    { value: "recovering", label: "Recovering" },
    { value: "beginner", label: "Beginner" },
    { value: "intermediate", label: "Intermediate" },
    { value: "advanced", label: "Advanced" },
  ],
  daysOfWeek: [
    { value: "Monday", label: "Monday" },
    { value: "Tuesday", label: "Tuesday" },
    { value: "Wednesday", label: "Wednesday" },
    { value: "Thursday", label: "Thursday" },
    { value: "Friday", label: "Friday" },
    { value: "Saturday", label: "Saturday" },
    { value: "Sunday", label: "Sunday" },
  ],
  buddyTypes: [
    { value: "encourager", label: "Encourager" },
    { value: "competitor", label: "Competitor" },
    { value: "trainer", label: "Trainer" },
    { value: "accountability-partner", label: "Accountability Partner" },
    { value: "learning-buddy", label: "Learning Buddy" },
    { value: "social-butterfly", label: "Social Butterfly" },
    { value: "early-riser", label: "Early Riser" },
    { value: "night-owl", label: "Night Owl" },
    { value: "solo-booster", label: "Solo Booster" },
    { value: "explorer", label: "Explorer" },
    { value: "flexible-partner", label: "Flexible Partner" },
  ],
  characters: [
    { name: "Batgirl", image: Batgirl },
    { name: "Nightwing", image: Nightwing },
    { name: "Red Hood", image: RedHood },
    { name: "Robin", image: Robin },
    { name: "Renee Montoya", image: Renne },
    { name: "Lucius Fox", image: Lucius },
    { name: "Court of Owls", image: Owl },
    { name: "Harley Quinn", image: Harley },
    { name: "Mr. Freeze", image: Freeze },
    { name: "Clayface", image: Clay },
    { name: "League of Shadows", image: Shadow },
    { name: "Penguin", image: Penguin },
    { name: "Bruce Wayne/Batman", image: Bruce },
  ],
};